language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install pytest pytest-cov coveralls
script:
  - py.test -v --cov=duct.py test_duct.py
after_success:
  - coveralls
