language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install pytest pytest-cov coveralls
script:
  # First run tests without installing pathlib. Use this run for coverage.
  - py.test -v test_duct.py --cov=duct.py
  # Then test again with pathlib installed. (Redundant on Python 3.4+.)
  - pip install pathlib
  - py.test -v test_duct.py
after_success:
  - coveralls
