language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
  - "nightly"
install:
  - pip install pytest pytest-cov coveralls
script:
  - py.test test_duct.py --cov=duct --cov-config=.coveragerc
after_success:
  - coveralls
